# Install pre-commit hooks via
# pre-commit install

repos:
  - repo: local
    hooks:
      - id: update-get_info
        name: Update function info
        entry: python _nx_parallel/update_get_info.py
        language: system
        pass_filenames: false
      - id: update-__init__.py
        name: Update __init__.py
        entry: git add _nx_parallel/__init__.py
        language: system
        pass_filenames: false
  - repo: https://github.com/adamchainz/blacken-docs
    rev: 1.16.0
    hooks:
      - id: blacken-docs
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.1.0
    hooks:
      - id: prettier
        files: \.(html|md|toml|yml|yaml)
        args: [--prose-wrap=preserve]
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.1.8
    hooks:
      - id: ruff
        args:
          - --fix
      - id: ruff-format
