[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "nx-parallel"
authors = [
    {name = "NetworkX Devs", email = "networkx-core@discuss.scientific-python.org"},
]
description = "An experimental parallel backend for NetworkX"
readme = "README.md"
requires-python = ">=3.10"
keywords = ["networkx", "algorithms", "parallel"]
license = {text = "BSD-3-Clause"}
classifiers = [
    "Programming Language :: Python :: 3",
]
dependencies = [
    "networkx",
    "joblib"
]
dynamic = ["version"]

[tool.hatch.build.targets.wheel]
packages = ["_nx_parallel", "nx_parallel",]

[project.optional-dependencies]
developer = [
    'pre-commit',
    'pytest',
]

[project.entry-points."networkx.backends"]
parallel = "nx_parallel.interface:Dispatcher"

[project.entry-points."networkx.backend_info"]
parallel = "_nx_parallel:get_info"

[tool.setuptools]
py-modules = []

[tool.ruff]
line-length = 88
target-version = 'py310'

[tool.ruff.per-file-ignores]
"__init__.py" = ['I', 'F403']
