name: Update get_info on approval
on:
  pull_request_review:
    types: [submitted]

jobs:
  approved:
    if: github.event.review.state == 'approved'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Update __init__.py file
        run: |
          sh _nx_parallel/script.sh

      - name: Check if __init__.py has been modified
        id: check_changes
        run: |
          git diff --exit-code --name-only || echo "::set-output name=modified::true"
        continue-on-error: true

      - name: Commit modified files
        if: steps.check_changes.outputs.modified == 'true'
        run: |
          git config --global user.email "1509aditi@gmail.com"
          git config --global user.name "Aditi Juneja"
          git add .
          git commit -m "Update __init__.py"
          git push origin ${{ github.head_ref }}
